# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RSEQ Team Calendar
version: "1.2.2"
slug: rseq_team_calendar
description: "Scrape le calendrier RSEQ d'une équipe ou de plusieurs équipes et publie le prochain match via MQTT (optionnel: création d'événements HA)."
url: "https://github.com/Frazou1/rseq_calendar"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw

options:
  # ----- NOUVEAU (facultatif) : multi-équipes -----
  entity_prefix: "rseq"
  teams: []
  # ----- Mode legacy : une seule équipe -----
  team_url: "https://diffusion.rseq.ca/Default?Type=Team&TeamId=3a82359e-d32c-43b2-ba3b-5d942d5d2c5f"

  update_interval: 3600

  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "monuser"
  mqtt_password: "monpassword"
  discovery_prefix: "homeassistant"

  # (Optionnel) création d'événements dans HA
  ha_url: "http://homeassistant.local:8123"
  ha_token: ""
  ha_calendar_entity: "calendar.rseq_equipes"

schema:
  entity_prefix: str?
  teams:
    - name: str
      team_url: str
  team_url: str?                   # legacy
  update_interval: int(30,86400)
  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_username: str
  mqtt_password: str
  discovery_prefix: str
  ha_url: str
  ha_token: str
  ha_calendar_entity: str

build:
  builder: docker
  file: Dockerfile
