# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RSEQ Team Calendar
version: "1.2.0"
slug: rseq_team_calendar
description: "Scrape un ou plusieurs calendriers RSEQ et publie le prochain match (1 sensor par équipe) via MQTT. Optionnel: création d’événements HA."
url: "https://github.com/Frazou1/rseq_calendar"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw

options:
  # --- NOUVEAU: multi-équipes (1 sensor par entrée) ---
  entity_prefix: "rseq"  # préfixe des entity_id, ex: sensor.rseq_pierre
  teams:
    - name: "Pierre"
      team_url: "https://diffusion.rseq.ca/Default?Type=Team&TeamId=3a82359e-d32c-43b2-ba3b-5d942d5d2c5f"
    # - name: "Élise"
    #   team_url: "https://diffusion.rseq.ca/Default?Type=Team&TeamId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

  # --- Compat legacy (optionnel si vous gardez l'ancien mode 1 équipe) ---
  team_url: "https://diffusion.rseq.ca/Default?Type=Team&TeamId=3a82359e-d32c-43b2-ba3b-5d942d5d2c5f"

  update_interval: 3600  # secondes

  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "monuser"
  mqtt_password: "monpassword"
  discovery_prefix: "homeassistant"

  # (Optionnel) création d'événements dans HA
  ha_url: "http://homeassistant.local:8123"
  ha_token: ""                  # Jeton d'accès longue durée (ou vide si inutilisé)
  ha_calendar_entity: "calendar.rseq_equipes"

schema:
  entity_prefix: str?
  teams:
    - name: str
      team_url: str
  team_url: str?                          # legacy, optionnel
  update_interval: int(30, 86400)
  mqtt_host: str
  mqtt_port: int(1, 65535)
  mqtt_username: str
  mqtt_password: str
  discovery_prefix: str
  ha_url: str
  ha_token: str
  ha_calendar_entity: str

build:
  builder: docker
  file: Dockerfile
